### PR TITLE
tech(base): Add Spring Boot Base Setup

### PR DESCRIPTION
**Pull request by ramsunvtech**
Implements #6 

### Step 1: Search and Install Below VSCode Extension
    1. Language Support for Java(TM) by Red Hat
    2. Java Extension Pack
    3. Java Test Runner
    4. Maven for Java
    5. Spring Initializr

### Step 2: Generate Spring Boot Application
    1. Press - CTRL + P and Type "> Spring"
    2. Choose "Spring Initializr: Create a Maven Project."
    3. Choose Spring Boot Version "2.4.1"
    4. Choose Project Language as "Java"
    5. Type Group Id as "com.google.search" / "com.google"
    5. Type Artifact id as "google-search".
    6. Choose Packaging Type
    6. Choose Boot Version as "2.3.x".
    7. Choose Java Version as 1.8
    7. Choose Dependencies below.
        1. Spring Web
        2. Spring Boot DevTools - Fast Way to Restart mainly for development experience.
        3. Spring Boot Actuator - Not needed in initial Time
        4. Spring Configuration Processor - Read Yaml File / all type of Configuration File.
    8. Finally Hit Enter and choose the folder to download generate folders and files.
    9. Choose Folder to Generate into this Folder.

### CODE REVIEW

**Review by naveenvignesh5 — APPROVED** [review]

**Review by jpukg — APPROVED** [review]
Looks okay.

**Review by karthikeyanpa12 — APPROVED** [review]

**Review by yuvarajuv — APPROVED** [review]
Below are my doubts:

1. Which packing type we need to use in this project (jar/war).
2. We have to use the below command to run this application?
`./mvnw spring-boot:run  `

**Comment by shangan23** [comment]
> Implements #6
> 
> ## Steps To Implement Feature
> ### Step 1: Search and Install Below VSCode Extension
> ```
> 1. Language Support for Java(TM) by Red Hat
> 2. Java Extension Pack
> 3. Java Test Runner
> 4. Maven for Java
> 5. Spring Initializr
> ```
> 
> ### Step 2: Generate Spring Boot Application
> ```
> 1. Press - CTRL + P and Type "> Spring"
> 2. Choose "Spring Initializr: Create a Maven Project."
> 3. Choose Spring Boot Version "2.4.1"
> 4. Choose Project Language as "Java"
> 5. Type Group Id as "com.google.search" / "com.google"
> 5. Type Artifact id as "google-search".
> 6. Choose Packaging Type
> 6. Choose Boot Version as "2.3.x".
> 7. Choose Java Version as 1.8
> 7. Choose Dependencies below.
>     1. Spring Web
>     2. Spring Boot DevTools - Fast Way to Restart mainly for development experience.
>     3. Spring Boot Actuator - Not needed in initial Time
>     4. Spring Configuration Processor - Read Yaml File / all type of Configuration File.
> 8. Finally Hit Enter and choose the folder to download generate folders and files.
> 9. Choose Folder to Generate into this Folder.
> ```

@ramsunvtech 
- Why VScode and why not Eclipse or IntelliJ ?
- `GroupId` can be a generic name like com.webslate.search (or) googleserach

**Comment by naveenvignesh5** [comment]
@shangan23 @ramsunvtech 

I feel we don't want to hold onto this for that information requested.

We can refer the below setup tutorials for different environments.
1. VS Code - https://medium.com/better-programming/how-to-set-up-a-spring-boot-project-in-vs-code-b0ca013c66fb
2. IntelliJ - https://medium.com/danielpadua/java-spring-boot-intellij-idea-b919b0097a0
3. Eclipse - https://www.edureka.co/blog/spring-boot-setup-helloworld-microservices-example/

**Comment by shangan23** [comment]
> @shangan23 @ramsunvtech
> We can refer the below setup tutorials for different environments.
> 
> 1. VS Code - https://medium.com/better-programming/how-to-set-up-a-spring-boot-project-in-vs-code-b0ca013c66fb
> 2. IntelliJ - https://medium.com/danielpadua/java-spring-boot-intellij-idea-b919b0097a0
> 3. Eclipse - https://www.edureka.co/blog/spring-boot-setup-helloworld-microservices-example/
> 
> @shangan23 If this information is sufficient I believe we may kindly go forward this PR.

Thanks for the links Navee. I am good to go on this.
For embedded Tomcat I will refer some online resources and come back.

**Review by shangan23 — COMMENTED** [review]
Looks good to me

**Pull request merged**
